### ISSUE TITLE
Add support for target STM32L432 (Nucleo)

### ISSUE THREAD

**Issue by vkottler** [badgerloop-software/pod3_gcc#9]
Populate `proc/stm32L4xx` with necessary infrastructure to compile the source and flash this device.

Some of this will likely need to be aggregated from examples.

**Comment by csgreen3** [comment]
in the dev foler there is already support for the STM32l432

**Comment by vkottler** [comment]
I see that but a linker script for GCC is missing

**Comment by vkottler** [comment]
Which is no big deal, I'll just copy the one we have and change the addresses for flash and RAM

**Comment by vkottler** [comment]
Working with the new build
